#!/usr/bin/env python3
"""Turn an IEEE MA-L CSV into the sorted firmware index src/OuiData.gen.inc.

The device never parses the raw CSV. Lookup is a binary search over this
generated table, which lives in flash. Rules match src/Oui.cpp.
"""

import argparse
import csv
import hashlib
import sys

READ_CAP = 128
STORE_CAP = 64
ALLOWED = set("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 ._-&'(),/")


def sanitize_manufacturer(raw):
    if raw is None:
        return ""
    data = raw.encode("utf-8")[:READ_CAP]
    out = []
    for byte in data:
        char = chr(byte)
        if char in ALLOWED and len(out) < STORE_CAP:
            out.append(char)
    while out and out[-1] in " .":
        out.pop()
    while out and out[0] == " ":
        out.pop(0)
    return "".join(out)


def parse_assignment(text):
    if text is None:
        return None
    trimmed = text.strip(" ")
    if len(trimmed) == 6 and all(c in "0123456789abcdefABCDEF" for c in trimmed):
        hex_text = trimmed
    elif len(trimmed) == 8 and trimmed[2] == trimmed[5] and trimmed[2] in ":-":
        hex_text = trimmed[0:2] + trimmed[3:5] + trimmed[6:8]
        if not all(c in "0123456789abcdefABCDEF" for c in hex_text):
            return None
    else:
        return None
    return int(hex_text, 16)


def preferred_name(current, incoming):
    if not incoming:
        return current
    if not current:
        return incoming
    if incoming < current:
        return incoming
    return current


def self_test():
    samples = {
        "AABBCC": 0xAABBCC,
        "aa:bb:cc": 0xAABBCC,
        "AA-BB-CC": 0xAABBCC,
        "  aabbcc  ": 0xAABBCC,
    }
    for text, expect in samples.items():
        if parse_assignment(text) != expect:
            raise SystemExit("self-test parse failed for " + text)
    rejected = ["", "GG0000", "AA:BB:CC:DD", "AA:BB-CC", "AABBCCD", "AA:BB:CC extra", None]
    for text in rejected:
        if parse_assignment(text) is not None:
            raise SystemExit("self-test accepted malformed assignment")
    if sanitize_manufacturer("  Jetway Information Co., Ltd.  ") != "Jetway Information Co., Ltd":
        raise SystemExit("self-test sanitize failed")
    if sanitize_manufacturer("@@@") != "":
        raise SystemExit("self-test kept an empty name")
    if preferred_name("NETWORK RESEARCH CORPORATION", "CERN") != "CERN":
        raise SystemExit("self-test duplicate choice failed")
    if preferred_name("Acme", "") != "Acme":
        raise SystemExit("self-test empty incoming replaced a name")
    if preferred_name("Alpha", "Zebra") != "Alpha":
        raise SystemExit("self-test larger name replaced a smaller one")
    print("OUI_SELF_TEST=pass")


def build(csv_path, out_path):
    digest = hashlib.sha256()
    with open(csv_path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    source_sha = digest.hexdigest()
    chosen = {}
    rows = 0
    rejected = 0
    replaced = 0
    with open(csv_path, "r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None or "Assignment" not in reader.fieldnames or "Organization Name" not in reader.fieldnames:
            raise SystemExit("CSV is missing Assignment or Organization Name")
        for row in reader:
            rows += 1
            registry = (row.get("Registry") or "").strip()
            if registry != "MA-L":
                rejected += 1
                continue
            prefix = parse_assignment(row.get("Assignment") or "")
            name = sanitize_manufacturer(row.get("Organization Name") or "")
            if prefix is None or not name:
                rejected += 1
                continue
            current = chosen.get(prefix)
            if current is None:
                chosen[prefix] = name
                continue
            winner = preferred_name(current, name)
            if winner != current:
                replaced += 1
                chosen[prefix] = winner
            elif name != current:
                replaced += 1
    if not chosen:
        raise SystemExit("no MA-L records survived")
    offsets = {}
    blob_parts = []
    cursor = 0
    for name in sorted(set(chosen.values())):
        offsets[name] = cursor
        blob_parts.append(name)
        cursor += len(name) + 1
    prefixes = sorted(chosen)
    lines = [
        "// Generated by tools/oui/build_oui_index.py. Do not edit by hand.",
        "// Source: IEEE MA-L registry https://standards-oui.ieee.org/oui/oui.csv",
        "// Source-SHA256: %s" % source_sha,
        "// Rows read: %d. Records kept: %d. Rejected: %d. Duplicate names resolved: %d."
        % (rows, len(prefixes), rejected, replaced),
        "// Duplicate assignments keep the lexicographically smaller sanitized organization name.",
        "static const OuiEntry kOuiEntries[] = {",
    ]
    for prefix in prefixes:
        lines.append("    {0x%06Xu, %uu}," % (prefix, offsets[chosen[prefix]]))
    lines.append("};")
    lines.append("static const char kOuiNames[] =")
    for name in blob_parts:
        lines.append('"%s\\0"' % name)
    lines.append(";")
    lines.append("OuiTable embeddedOuiTable() {")
    lines.append("  OuiTable table;")
    lines.append("  table.entries = kOuiEntries;")
    lines.append("  table.count = static_cast<uint32_t>(sizeof(kOuiEntries) / sizeof(kOuiEntries[0]));")
    lines.append("  table.names = kOuiNames;")
    lines.append("  return table;")
    lines.append("}")
    lines.append("")
    with open(out_path, "w", encoding="ascii", newline="\n") as handle:
        handle.write("\n".join(lines))
    interest = []
    for prefix in (0x00005E, 0x003018):
        name = chosen.get(prefix)
        interest.append("%06X=%s" % (prefix, name if name else "MISSING"))
    print("OUI_BUILD=pass")
    print("OUI_SOURCE_SHA256=%s" % source_sha)
    print("OUI_ROWS=%d" % rows)
    print("OUI_KEPT=%d" % len(prefixes))
    print("OUI_REJECTED=%d" % rejected)
    print("OUI_REPLACED=%d" % replaced)
    print("OUI_NAMES=%d" % len(blob_parts))
    print("OUI_BLOB_BYTES=%d" % cursor)
    print("OUI_INTEREST %s" % " ".join(interest))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv")
    parser.add_argument("--out")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test or not args.csv:
        self_test()
    if args.csv:
        if not args.out:
            raise SystemExit("--out is required with --csv")
        build(args.csv, args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
